In [ ]:
#EXERCISE A,B,C

In [8]:
#EXERCISE A

import numpy as np #imports the numpy as np

A = np.array([
    [2, 4, 6],
    [24, 16, 8],     # This row contains integer values arranged in a nested list
    [25, 50, 75]
])


print("Shape:", A.shape)  #in this line Output will show the dimensions of the array 3 rows, 3 columns

print("Max using method:", A.max())  #finds and returns the largest value in the entire array


print("Max using function:", np.max(A)) #finds the maximum value

print("\nArray A:") #the \n creates a new blank line before printing
print(A)  #displays the entire array in matrix format


Shape: (3, 3)
Max using method: 75
Max using function: 75

Array A:
[[ 2  4  6]
 [24 16  8]
 [25 50 75]]


In [7]:
#EXERCISE B

import numpy as np #this will import the numpy library

B = np.ones((5, 5), dtype=int) # creates a 5x5 array with all values = 1

print("Array B:")
print(B) # Display the 5x5 array
print("Shape:", B.shape) # Returns the dimensions of the array 5 rows, 5 columns.
print("Size:", B.size)  # shows total number of values
print("Dimensions:", B.ndim) # it prints how many dimensions(which is 2)


Array B:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape: (5, 5)
Size: 25
Dimensions: 2


In [6]:
#EXERCISE C

import numpy as np

C = np.arange(-5, 6)  # Create an array from -5 to 5. The number 6 is the stop value, which is not included.
# np.arange() always stops before the stop value, so 5 is included but 6 is not.

result = C * 2  # multiply each value in the array by 2

print("Original array:", C)  # displays original numbers
print("Multiplied by 2:", result)  # Shows the result after multiplying by 2

Original array: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Multiplied by 2: [-10  -8  -6  -4  -2   0   2   4   6   8  10]
